version: '3'

services:
  consul-server-beta: &consul-server
    image: consul:1.0.6
    networks:
      - bearnet
    command: "agent -server -retry-join consul-server-alpha -client 0.0.0.0 -node consul-server-beta"

  consul-server-gamma:
    <<: *consul-server
    command: "agent -server -retry-join consul-server-alpha -client 0.0.0.0 -node consul-server-gamma"

  consul-server-alpha:
    image: consul:1.0.6
    networks:
      - bearnet
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0 -node consul-server-alpha"

networks:
  bearnet:
