version: '2.1'

services:
  kong-database:
    build: kong-database/
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - kongnet  
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 5
  kong-migration:
    image: kong:0.13.0
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    networks:
      - kongnet  
    command: kong migrations up
  kong:
    build: kong/
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    networks:
      - kongnet        
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 25s
      retries: 10

networks:
  kongnet:
   external:
     name: consul_bearnet